/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodePortableMapVersion {
  id: Buffer
  tree: NodeTreeRecord
  createdAtMillis?: string
  isHead: boolean
}
export interface NodePortableMapUpdate {
  kind: string
  previous?: Buffer
  current?: NodePortableMapVersion
}
export interface NodePortableVersionPrune {
  retained: Array<Buffer>
  removed: Array<Buffer>
}
export interface NodePortableIndexEntry {
  term: Buffer
  projection?: Buffer
}
export interface NodePortableIndexExtractRequest {
  primaryKey: Buffer
  sourceValue: Buffer
}
export interface NodePortableIndexedVersion {
  sourceVersion: Buffer
  catalogVersion?: Buffer
  indexCount: string
}
export interface NodePortableIndexedSnapshotId {
  sourceVersion: Buffer
  catalogVersion: Buffer
}
export interface NodePortableIndexedUpdate {
  kind: string
  previousSourceVersion?: Buffer
  current?: NodePortableIndexedVersion
}
export interface NodePortableIndexBuildResult {
  sourceVersion: Buffer
  indexVersion: Buffer
  catalogVersion: Buffer
  generation: string
  entries: string
  attempts: string
  activated: boolean
}
export interface NodePortableActiveIndexHealth {
  name: Buffer
  generation: string
  fingerprint: Buffer
  projection: string
  indexMapId: Buffer
  indexVersion: Buffer
}
export interface NodePortableIndexedMapHealth {
  sourceMapId: Buffer
  sourceVersion?: Buffer
  catalogVersion?: Buffer
  activeIndexes: Array<NodePortableActiveIndexHealth>
  supportsTransactions: boolean
}
export interface NodePortableIndexVerification {
  name: Buffer
  sourceVersion: Buffer
  expectedIndexVersion: Buffer
  actualIndexVersion: Buffer
  expectedEntries: string
  actualEntries: string
  semanticDifferences: string
  valid: boolean
  canonical: boolean
}
export interface NodePortableIndexedMapMetrics {
  normalizedSourceMutations: string
  recordsExtracted: string
  termsEmitted: string
  projectedBytes: string
  physicalUpserts: string
  physicalDeletes: string
  unchangedEmissionsSkipped: string
  sourceNodesWritten: string
  indexNodesWritten: string
  catalogNodesWritten: string
  retries: string
  buildAttempts: string
  verificationOutcomes: string
  retainedRoots: string
}
export interface NodePortableIndexedRetention {
  retainedSourceVersions: Array<Buffer>
  removedSourceVersions: Array<Buffer>
  retainedIndexVersions: Array<Buffer>
  removedIndexVersions: Array<Buffer>
  removedCatalogVersions: Array<Buffer>
  removedCheckpointRecords: string
  removedNamedRoots: Array<Buffer>
}
export interface NodePortableIndexMatch {
  term: Buffer
  primaryKey: Buffer
  projection?: Buffer
}
export interface NodePortableIndexedSource {
  term: Buffer
  primaryKey: Buffer
  projection?: Buffer
  sourceValue: Buffer
}
export interface NodePortableIndexPage {
  matches: Array<NodePortableIndexMatch>
  nextCursor?: Buffer
}
export interface NodePortableProximityRecord {
  key: Buffer
  vector: Float32Array
  value: Buffer
}
export interface NodePortableExactProximityRecord {
  vector: Array<number>
  value: Buffer
}
export interface NodePortableProximityConfig {
  dimensions: number
  metric: string
  logChunkSize: number
  levelHashSeed: string
  minPageBytes: number
  targetPageBytes: number
  maxPageBytes: number
  overflowHashSeed: string
  inlineThresholdBytes: number
  scalarQuantizationGroupSize?: number
}
export interface NodePortableProximityMutation {
  key: Buffer
  vector?: Float32Array
  value?: Buffer
}
export interface NodePortableProximityMutationStats {
  directoryEntriesScanned: string
  directoryNodesRead: string
  directoryNodesRebuilt: string
  directoryNodesWritten: string
  directoryNodesReused: string
  directoryLevelsRebuilt: string
  directoryRightEdgeRebuilt: boolean
  recordsRebuilt: string
  nodesRead: string
  nodesWritten: string
  nodesReused: string
  distanceEvaluations: string
  fullProximityRebuild: boolean
}
export interface NodePortableProximityVerification {
  recordCount: string
  proximityNodeCount: string
  externalVectorCount: string
  quantizedNodeCount: string
  scalarQuantizerCount: string
  overflowPageCount: string
  overflowDirectoryCount: string
  maximumLevel: number
  maximumNodeBytes: string
  distanceChecks: string
}
export interface NodePortableStructuralVerification {
  descriptor: Buffer
  objectCount: string
  summary: NodePortableProximityVerification
}
export interface NodePortableNeighbor {
  key: Buffer
  value: Buffer
  distance: number
}
export interface NodePortableSearchBudget {
  maxNodes?: string
  maxCommittedBytes?: string
  maxDistanceEvaluations?: string
  maxFrontierEntries?: string
}
export interface NodePortableSearchFilter {
  kind: string
  start?: Buffer
  rangeEnd?: Buffer
  prefix?: Buffer
  eligibleKeys: Array<Buffer>
}
export interface NodePortableSearchRequest {
  query: Float32Array
  k: string
  policy: string
  adaptiveQuality?: string
  budget: NodePortableSearchBudget
  filter: NodePortableSearchFilter
  kernel: string
  backend: string
  hnswEfSearch?: number
  pqRerankMultiplier?: number
}
export interface NodePortableHnswConfig {
  maxConnections: number
  efConstruction: number
  efSearch: number
  levelBits: number
  overfetchMultiplier: number
  seed: string
  routingVectorEncoding: string
}
export interface NodePortableHnswBuildLimits {
  maxRecords?: string
  maxOwnedBytes?: string
  maxDistanceEvaluations?: string
  workerThreads: string
  maxEncodedGraphBytes?: string
}
export interface NodePortableHnswBuildStats {
  records: string
  distanceEvaluations: string
  directedEdges: string
  maximumLevel: number
  ownedBytes: string
  encodedGraphBytes: string
}
export interface NodePortablePqConfig {
  subquantizers: number
  centroidsPerSubquantizer: number
  trainingIterations: number
  rerankMultiplier: number
  seed: string
  maxTrainingVectors: string
}
export interface NodePortablePqBuildLimits {
  maxTrainingVectors?: string
  maxTrainingBytes?: string
  maxTemporaryCodeBytes?: string
  maxDistanceEvaluations?: string
  maxEncodedOutputBytes?: string
  maxWorkerThreads?: string
}
export interface NodePortablePqBuildStats {
  trainingDistanceEvaluations: string
  encodingDistanceEvaluations: string
  encodedVectors: string
  trainingVectors: string
  trainingBytes: string
  encodedOutputBytes: string
}
export interface NodePortablePqQuality {
  meanSquaredError: number
  maximumSquaredError: number
}
export interface NodePortableCompositeConfig {
  maxDeltaRecords: string
  maxShadowRecords: string
  maxDeltaRatioPpm: number
  maxShadowRatioPpm: number
  baseOverfetchMultiplier: number
}
export interface NodePortableCompositeBuildLimits {
  maxDiffEntries?: string
  maxOwnedBytes?: string
  maxEncodedOutputBytes?: string
  maxDistanceEvaluations?: string
}
export interface NodePortableCompositeBuildStats {
  diffEntries: string
  insertedRecords: string
  vectorUpdatedRecords: string
  valueOnlyRecords: string
  deletedRecords: string
  deltaRecords: string
  shadowRecords: string
  ownedBytesPeak: string
  encodedOutputBytes: string
  distanceEvaluations: string
}
export interface NodePortableFullRebuildReason {
  kind: string
  actual: string
  maximum: string
}
export interface NodePortableCompositeRebuildOptions {
  hnswLimits: NodePortableHnswBuildLimits
  pqWorkerThreads: string
  pqLimits: NodePortablePqBuildLimits
}
export interface NodePortableCatalogEntry {
  kind: string
  configurationFingerprint: Buffer
  manifest: Buffer
}
export interface NodePortableSearchStats {
  levelsVisited: string
  nodesRead: string
  bytesRead: string
  physicalBytesRead: string
  committedBytes: string
  distanceEvaluations: string
  quantizedDistanceEvaluations: string
  rerankedCandidates: string
  frontierPeak: string
  candidateHandlesPeak: string
  candidateRetainedBytesPeak: string
}
export interface NodePortableProximitySearchRuntimePolicy {
  maxEntries: string
  maxBytes: string
  authoritativeMaxBytes: string
  hnswMaxBytes: string
  pqMaxBytes: string
}
export interface NodePortableProximitySearchRuntimeStats {
  physicalReads: string
  physicalBytesRead: string
}
export declare function defaultProximitySearchRuntimePolicy(): NodePortableProximitySearchRuntimePolicy
export interface NodePortableSearchResult {
  neighbors: Array<NodePortableNeighbor>
  stats: NodePortableSearchStats
  completion: string
  backend: string
  planFormatVersion: number
}
export interface NodePortableSearchProofVerification {
  result: NodePortableSearchResult
  claim: string
  terminalLowerBound?: number
  replayedEvents: string
}
export interface NodePortableProofVerification {
  valid: boolean
  exists: boolean
  value?: Buffer
}
export interface NodePortableMaintenanceSummary {
  itemCount: string
  byteCount: string
}
export interface NodePortableCatalogVerification {
  head: Buffer
  versionCount: string
  reachableNodes: string
  reachableBytes: string
}
export interface NodePortableVersionedMapBatchResult {
  version: NodePortableMapVersion
  stats: NodeBatchApplyStatsRecord
}
export interface NodePortableReadScanOutcome {
  visited: string
  stopped: boolean
}
export interface NodePortableMapChangeEvent {
  previous?: Buffer
  current: NodePortableMapVersion
  diffs: Array<NodeDiffRecord>
}
export interface NodePortableVersionedTransactionCommit {
  applied: boolean
  versions: Array<NodePortableMapVersion>
  conflictMapId?: Buffer
  conflictCurrent?: NodePortableMapVersion
}
export interface NodePortableSecondaryIndexLimits {
  maxTermBytes: string
  maxProjectionBytes: string
  maxAllValueBytes: string
  maxTermsPerRecord: string
  maxProjectedBytesPerRecord: string
  maxDerivedMutationsPerTransaction: string
  maxProjectedBytesPerTransaction: string
  maxIndexes: string
  buildPageSize: string
  maxTemporarySortBytes: string
  maxBundleNodes: string
  maxBundleBytes: string
  maxVerificationEntries: string
  maxWriteRetries: string
  maxBuildRetries: string
}
export interface NodeRemoteStoreCapabilitiesRecord {
  nativeBatchReads: boolean
  atomicBatchWrites: boolean
  nodeScan: boolean
  hints: boolean
  atomicNodesAndHint: boolean
  rootScan: boolean
  rootCompareAndSwap: boolean
  transactions: boolean
  readParallelism: number
}
export interface NodeRemoteStoreLimitsRecord {
  maxBatchReadItems?: number
  maxBatchWriteItems?: number
  maxTransactionOperations?: number
  maxNodeBytes?: string
}
export interface NodeRemoteStoreDescriptorRecord {
  protocolMajor: number
  adapterName: string
  provider: string
  schemaVersion: number
  capabilities: NodeRemoteStoreCapabilitiesRecord
  limits: NodeRemoteStoreLimitsRecord
}
export interface NodeRemoteStoreErrorRecord {
  code: string
  message: string
  retryable: boolean
  providerCode?: string
}
export interface NodeRemoteOptionalBytesRecord {
  present: boolean
  value: Buffer
}
export interface NodeRemoteMutationRecord {
  cid: Buffer
  value: NodeRemoteOptionalBytesRecord
}
export interface NodeRemoteEntryRecord {
  cid: Buffer
  node: Buffer
}
export interface NodeRemotePublicationHintRecord {
  namespace: Buffer
  key: Buffer
  value: Buffer
}
export interface NodeRemoteNamedRootRecord {
  name: Buffer
  manifest: Buffer
}
export interface NodeRemoteRootConditionRecord {
  name: Buffer
  expected: NodeRemoteOptionalBytesRecord
}
export interface NodeRemoteRootWriteRecord {
  name: Buffer
  replacement: NodeRemoteOptionalBytesRecord
}
export interface NodeRemoteRootCasRecord {
  applied: boolean
  current: NodeRemoteOptionalBytesRecord
}
export interface NodeRemoteTransactionConflictRecord {
  name: Buffer
  expected: NodeRemoteOptionalBytesRecord
  current: NodeRemoteOptionalBytesRecord
}
export interface NodeRemoteTransactionRecord {
  applied: boolean
  conflict?: NodeRemoteTransactionConflictRecord
}
export interface NodeRemoteStoreRequest {
  operation: string
  requestId: string
  bytes?: Array<Buffer>
  optionalBytes?: Array<NodeRemoteOptionalBytesRecord>
  mutations?: Array<NodeRemoteMutationRecord>
  entries?: Array<NodeRemoteEntryRecord>
  publicationOrigin?: number
  publicationHint?: NodeRemotePublicationHintRecord
  conditions?: Array<NodeRemoteRootConditionRecord>
  roots?: Array<NodeRemoteRootWriteRecord>
}
export interface NodeRemoteStoreResponse {
  descriptor?: NodeRemoteStoreDescriptorRecord
  optionalBytes?: NodeRemoteOptionalBytesRecord
  optionalValues?: Array<NodeRemoteOptionalBytesRecord>
  bytesValues?: Array<Buffer>
  namedRoots?: Array<NodeRemoteNamedRootRecord>
  rootCas?: NodeRemoteRootCasRecord
  transaction?: NodeRemoteTransactionRecord
  error?: NodeRemoteStoreErrorRecord
}
export interface NodeTreeRecord {
  root?: Buffer
  config?: NodeConfigRecord
}
export interface NodeEntryRecord {
  key: Buffer
  value: Buffer
}
export interface NodeScanOutcomeRecord {
  visited: string
  stopped: boolean
}
export interface NodeDiffRecord {
  kind: string
  key: Buffer
  value?: Buffer
  old?: Buffer
  newValue?: Buffer
}
export interface NodeMutationRecord {
  kind: string
  key: Buffer
  value?: Buffer
}
export interface NodeEncodingRecord {
  kind: string
  customName?: string
}
export interface NodeConfigRecord {
  minChunkSize: string
  maxChunkSize: string
  chunkingFactor: number
  hashSeed: string
  encoding: NodeEncodingRecord
  nodeCacheMaxNodes?: string
  nodeCacheMaxBytes?: string
  formatBytes?: Buffer
}
export interface NodeParallelConfigRecord {
  maxThreads: string
  parallelismThreshold: string
}
export interface NodeSnapshotBundleNodeRecord {
  cid: Buffer
  bytes: Buffer
}
export interface NodeSnapshotBundleRecord {
  formatVersion: number
  tree: NodeTreeRecord
  nodes: Array<NodeSnapshotBundleNodeRecord>
}
export interface NodeSnapshotBundleSummaryRecord {
  formatVersion: number
  root?: Buffer
  nodeCount: string
  byteCount: string
  minNodeBytes: string
  maxNodeBytes: string
}
export interface NodeSnapshotBundleVerificationRecord {
  valid: boolean
  summary: NodeSnapshotBundleSummaryRecord
  reachableNodes: string
  reachableBytes: string
  missingCids: Array<Buffer>
  extraCids: Array<Buffer>
}
export interface NodeBatchApplyStatsRecord {
  inputMutations: string
  effectiveMutations: string
  preprocessInputSorted: boolean
  entriesStreamed: string
  nodesRead: string
  writtenNodes: string
  nodesReused: string
  bytesRead: string
  writtenBytes: string
  resyncDistanceEntries: string
  resyncDistanceNodes: string
  usedKeyStableFastPath: boolean
  usedBatchedValueUpdatePath: boolean
  parallelWidth: string
  parallelTasks: string
  structuralIslands: string
  coalescedIslands: string
}
export interface NodeBatchApplyResultRecord {
  tree: NodeTreeRecord
  stats: NodeBatchApplyStatsRecord
}
export interface NodeWriteStatsRecord {
  inputMutations: string
  effectiveMutations: string
  entriesStreamed: string
  nodesRead: string
  nodesWritten: string
  nodesReused: string
  bytesRead: string
  bytesWritten: string
  resyncDistanceEntries: string
  resyncDistanceNodes: string
  usedKeyStableFastPath: boolean
  usedBatchedValueUpdatePath: boolean
  parallelWidth: string
  parallelTasks: string
  structuralIslands: string
  coalescedIslands: string
}
export interface NodeWriteResultRecord {
  tree: NodeTreeRecord
  stats: NodeWriteStatsRecord
}
export interface NodeHostStoreEmptyRequest {
  
}
export interface NodeHostStoreKeyRequest {
  key: Buffer
}
export interface NodeHostStorePutRequest {
  key: Buffer
  value: Buffer
}
export interface NodeHostStoreBatchRequest {
  ops: Array<NodeMutationRecord>
}
export interface NodePublicationOriginRecord {
  code: number
}
export interface NodeHostStorePublicationHintRecord {
  namespace: Buffer
  key: Buffer
  value: Buffer
}
export interface NodeHostStorePublicationRequest {
  nodes: Array<NodeEntryRecord>
  hint?: NodeHostStorePublicationHintRecord
  origin: NodePublicationOriginRecord
}
export interface NodeHostStoreBatchGetRequest {
  keys: Array<Buffer>
}
export interface NodeHostStoreHintRequest {
  namespace: Buffer
  key: Buffer
}
export interface NodeHostStorePutHintRequest {
  namespace: Buffer
  key: Buffer
  value: Buffer
}
export interface NodeHostStoreRootRequest {
  name: Buffer
}
export interface NodeHostStorePutRootRequest {
  name: Buffer
  manifest: Buffer
}
export interface NodeHostStoreCasRootRequest {
  name: Buffer
  expected?: Buffer
  replacement?: Buffer
}
export interface NodeHostStoreBytesResult {
  value?: Buffer
  ok: boolean
  error?: string
}
export interface NodeHostStoreUnitResult {
  error?: string
}
export interface NodeHostStoreBoolResult {
  value: boolean
  error?: string
}
export interface NodeHostStoreBatchGetResult {
  values: Array<NodeHostStoreBytesResult>
  error?: string
}
export interface NodeHostStoreListBytesResult {
  values: Array<Buffer>
  error?: string
}
export interface NodeHostStoreRootResult {
  value?: Buffer
  error?: string
}
export interface NodeHostStoreNamedRootManifest {
  name: Buffer
  manifest: Buffer
}
export interface NodeHostStoreListRootsResult {
  values: Array<NodeHostStoreNamedRootManifest>
  error?: string
}
export interface NodeHostStoreCasResult {
  applied: boolean
  current?: Buffer
  error?: string
}
export interface NodeRangeCursorRecord {
  afterKey?: Buffer
}
export interface NodeReverseCursorRecord {
  beforeKey?: Buffer
}
export interface NodeRangeBoundsRecord {
  start: Buffer
  end?: Buffer
}
export interface NodeRangePageRecord {
  entries: Array<NodeEntryRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeReversePageRecord {
  entries: Array<NodeEntryRecord>
  nextCursor?: NodeReverseCursorRecord
}
export interface NodeCursorWindowRecord {
  positionKey?: Buffer
  positionValue?: Buffer
  found: boolean
  entries: Array<NodeEntryRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeDiffPageRecord {
  diffs: Array<NodeDiffRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeConflictRecord {
  key: Buffer
  base?: Buffer
  left?: Buffer
  right?: Buffer
}
export interface NodeResolutionRecord {
  kind: string
  value?: Buffer
}
export interface NodeCrdtResolutionRecord {
  kind: string
  value?: Buffer
}
export interface NodeConflictPageRecord {
  conflicts: Array<NodeConflictRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeDiffTraversalStatsRecord {
  comparedNodes: string
  reusedSubtrees: string
  addedSubtrees: string
  removedSubtrees: string
  collectedFallbacks: string
  emittedDiffs: string
}
export interface NodeStructuralDiffPageRecord {
  diffs: Array<NodeDiffRecord>
  nextCursorJson?: string
  stats: NodeDiffTraversalStatsRecord
  nextCursor?: NodeStructuralDiffCursorRecord
}
export interface NodeStructuralDiffCursorRecord {
  baseRoot?: Buffer
  otherRoot?: Buffer
  markers: Array<NodeStructuralDiffMarkerRecord>
  pending: Array<NodeDiffRecord>
}
export interface NodeStructuralDiffMarkerRecord {
  kind: string
  baseCid?: Buffer
  otherCid?: Buffer
  spanEnd?: Buffer
  cid?: Buffer
}
export interface NodeMergeTraceRecord {
  events: Array<NodeMergeTraceEventRecord>
}
export interface NodeMergeTraceEventRecord {
  kind: string
  fastPath?: string
  cid?: Buffer
  reuseReason?: string
  level?: string
  entries?: string
  firstKey?: Buffer
  lastKey?: Buffer
  stage?: string
  key?: Buffer
  resolution?: string
  fallbackReason?: string
  diffStats?: NodeDiffTraversalStatsRecord
  rightChanges?: string
  mutations?: string
  appendOnly?: boolean
}
export interface NodeMergeExplanationRecord {
  result?: NodeTreeRecord
  error?: string
  traceJson: string
  trace: NodeMergeTraceRecord
}
export interface NodeNamedRootRecord {
  name: Buffer
  tree: NodeTreeRecord
}
export interface NodeRootManifestRecord {
  tree: NodeTreeRecord
  createdAtMillis?: string
  updatedAtMillis?: string
}
export interface NodeNamedRootManifestRecord {
  name: Buffer
  manifest: NodeRootManifestRecord
}
export interface NodeNamedRootSelectionRecord {
  roots: Array<NodeNamedRootRecord>
  missingNames: Array<Buffer>
}
export interface NodeNamedRootUpdateRecord {
  applied: boolean
  conflict: boolean
  current?: NodeTreeRecord
}
export interface NodeTransactionConflictRecord {
  name: Buffer
  expected?: NodeRootManifestRecord
  current?: NodeRootManifestRecord
}
export interface NodeTransactionUpdateRecord {
  applied: boolean
  conflict: boolean
  nodesWritten: string
  rootsWritten: string
  conflictDetail?: NodeTransactionConflictRecord
}
export interface NodeSnapshotNamespaceRecord {
  kind: string
  customPrefix?: Buffer
}
export interface NodeSnapshotRecord {
  id: Buffer
  name: Buffer
  tree: NodeTreeRecord
  createdAtMillis?: string
  updatedAtMillis?: string
}
export interface NodeSnapshotSelectionRecord {
  snapshots: Array<NodeSnapshotRecord>
  missingIds: Array<Buffer>
}
export interface NodeKeyProofRecord {
  root?: Buffer
  key: Buffer
  pathNodeBytes: Array<Buffer>
}
export interface NodeKeyProofVerificationRecord {
  valid: boolean
  exists: boolean
  absence: boolean
  root?: Buffer
  key: Buffer
  value?: Buffer
}
export interface NodeMultiKeyProofRecord {
  root?: Buffer
  keys: Array<Buffer>
  pathNodeBytes: Array<Buffer>
}
export interface NodeMultiKeyProofVerificationRecord {
  valid: boolean
  root?: Buffer
  results: Array<NodeKeyProofVerificationRecord>
}
export interface NodeRangeProofRecord {
  root?: Buffer
  start: Buffer
  end?: Buffer
  pathNodeBytes: Array<Buffer>
}
export interface NodeRangeProofVerificationRecord {
  valid: boolean
  root?: Buffer
  start: Buffer
  end?: Buffer
  entries: Array<NodeEntryRecord>
}
export interface NodeRangePageProofRecord {
  root?: Buffer
  after?: Buffer
  end?: Buffer
  pathNodeBytes: Array<Buffer>
}
export interface NodeRangePageProofVerificationRecord {
  valid: boolean
  root?: Buffer
  after?: Buffer
  end?: Buffer
  entries: Array<NodeEntryRecord>
}
export interface NodeProvedRangePageRecord {
  page: NodeRangePageRecord
  proof: NodeRangePageProofRecord
}
export interface NodeDiffPageProofRecord {
  base: NodeRangePageProofRecord
  other: NodeRangePageProofRecord
  lookaheadBase?: NodeKeyProofRecord
  lookaheadOther?: NodeKeyProofRecord
  requestedEnd?: Buffer
  limit: string
}
export interface NodeDiffPageProofVerificationRecord {
  valid: boolean
  baseValid: boolean
  otherValid: boolean
  lookaheadValid: boolean
  baseRoot?: Buffer
  otherRoot?: Buffer
  after?: Buffer
  requestedEnd?: Buffer
  proofEnd?: Buffer
  limit: string
  diffs: Array<NodeDiffRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeProvedDiffPageRecord {
  page: NodeDiffPageRecord
  proof: NodeDiffPageProofRecord
}
export interface NodeProofBundleSummaryRecord {
  version: string
  kind: string
  root?: Buffer
  otherRoot?: Buffer
  keyCount: string
  pathNodeCount: string
  start?: Buffer
  end?: Buffer
  after?: Buffer
  requestedEnd?: Buffer
  limit?: string
  hasLookahead: boolean
}
export interface NodeProofBundleVerificationRecord {
  summary: NodeProofBundleSummaryRecord
  valid: boolean
  existsCount: string
  absenceCount: string
  entryCount: string
  diffCount: string
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeAuthenticatedProofEnvelopeRecord {
  algorithm: string
  keyId: Buffer
  proofBundle: Buffer
  context: Buffer
  issuedAtMillis?: string
  expiresAtMillis?: string
  nonce: Buffer
  signature: Buffer
}
export interface NodeAuthenticatedProofEnvelopeVerificationRecord {
  valid: boolean
  signatureValid: boolean
  timeValid: boolean
  notYetValid: boolean
  expired: boolean
  algorithm: string
  keyId: Buffer
  proofBundle: Buffer
  context: Buffer
  issuedAtMillis?: string
  expiresAtMillis?: string
  nonce: Buffer
}
export interface NodeAuthenticatedProofBundleVerificationRecord {
  valid: boolean
  envelope: NodeAuthenticatedProofEnvelopeVerificationRecord
  proof?: NodeProofBundleVerificationRecord
  proofError?: string
}
export interface NodeNamedRootRetentionRecord {
  kind: string
  names: Array<Buffer>
  prefix?: Buffer
  count?: string
  minUpdatedAtMillis?: string
}
export interface NodeCacheStatsRecord {
  cachedNodes: string
  cachedBytes: string
  pinnedNodes: string
  pinnedBytes: string
}
export interface NodeMetricsRecord {
  nodeCacheHits: string
  nodeCacheMisses: string
  nodeCacheEvictions: string
  nodesRead: string
  bytesRead: string
  nodesWritten: string
  bytesWritten: string
  storeGetCalls: string
  storeBatchGetCalls: string
  storeBatchGetKeys: string
  storePutCalls: string
  storeBatchPutCalls: string
  storeBatchPutNodes: string
}
export interface NodeChangedSpanRecord {
  start: Buffer
  end?: Buffer
}
export interface NodeChangedSpanHintRecord {
  baseRoot?: Buffer
  changedRoot?: Buffer
  spans: Array<NodeChangedSpanRecord>
}
export interface NodeGcReachabilityRecord {
  liveCids: Array<Buffer>
  liveNodes: string
  liveBytes: string
  leafNodes: string
  internalNodes: string
}
export interface NodeGcPlanRecord {
  reachability: NodeGcReachabilityRecord
  candidateNodes: string
  reclaimableCids: Array<Buffer>
  reclaimableNodes: string
  reclaimableBytes: string
  missingCandidates: string
}
export interface NodeGcSweepRecord {
  plan: NodeGcPlanRecord
  deletedNodes: string
  deletedBytes: string
}
export interface NodeMissingNodePlanRecord {
  requiredCids: Array<Buffer>
  requiredNodes: string
  requiredBytes: string
  missingCids: Array<Buffer>
  missingNodes: string
  missingBytes: string
}
export interface NodeMissingNodeCopyRecord {
  plan: NodeMissingNodePlanRecord
  copiedNodes: string
  copiedBytes: string
}
export interface NodeBlobRefRecord {
  cid: Buffer
  len: string
}
export interface NodeLargeValueConfigRecord {
  inlineThreshold: string
}
export interface NodeValueRefRecord {
  kind: string
  value?: Buffer
  blob?: NodeBlobRefRecord
}
export interface NodeBlobGcReachabilityRecord {
  liveBlobs: Array<NodeBlobRefRecord>
  liveBlobCount: string
  liveBlobBytes: string
  scannedNodes: string
  scannedValues: string
}
export interface NodeBlobGcPlanRecord {
  reachability: NodeBlobGcReachabilityRecord
  candidateBlobs: string
  reclaimableBlobs: Array<NodeBlobRefRecord>
  reclaimableBlobCount: string
  reclaimableBlobBytes: string
  missingCandidates: string
}
export interface NodeBlobGcSweepRecord {
  plan: NodeBlobGcPlanRecord
  deletedBlobs: string
  deletedBlobBytes: string
}
export interface NodeCrdtConfigRecord {
  strategy: string
  deletePolicy: string
}
export interface NodeTimestampedValueRecord {
  value: Buffer
  timestamp: string
}
export interface NodeTombstoneMetadataRecord {
  key: string
  value: Buffer
}
export interface NodeTombstoneRecord {
  actor: Buffer
  timestampMillis: string
  causalMetadata: Array<NodeTombstoneMetadataRecord>
}
export declare function cidFromBytes(bytes: Buffer): Buffer
export declare function nodeBytesRoundTrip(bytes: Buffer): Buffer
export declare function nodeCidFromBytes(bytes: Buffer): Buffer
export declare function verifyKeyProof(proof: NodeKeyProofRecord): NodeKeyProofVerificationRecord
export declare function verifyMultiKeyProof(proof: NodeMultiKeyProofRecord): NodeMultiKeyProofVerificationRecord
export declare function verifyRangeProof(proof: NodeRangeProofRecord): NodeRangeProofVerificationRecord
export declare function verifyRangePageProof(proof: NodeRangePageProofRecord): NodeRangePageProofVerificationRecord
export declare function verifyDiffPageProof(proof: NodeDiffPageProofRecord): NodeDiffPageProofVerificationRecord
export declare function keyProofToBytes(proof: NodeKeyProofRecord): Buffer
export declare function keyProofFromBytes(bytes: Buffer): NodeKeyProofRecord
export declare function multiKeyProofToBytes(proof: NodeMultiKeyProofRecord): Buffer
export declare function multiKeyProofFromBytes(bytes: Buffer): NodeMultiKeyProofRecord
export declare function rangeProofToBytes(proof: NodeRangeProofRecord): Buffer
export declare function rangeProofFromBytes(bytes: Buffer): NodeRangeProofRecord
export declare function rangePageProofToBytes(proof: NodeRangePageProofRecord): Buffer
export declare function rangePageProofFromBytes(bytes: Buffer): NodeRangePageProofRecord
export declare function diffPageProofToBytes(proof: NodeDiffPageProofRecord): Buffer
export declare function diffPageProofFromBytes(bytes: Buffer): NodeDiffPageProofRecord
export declare function inspectProofBundle(bytes: Buffer): NodeProofBundleSummaryRecord
export declare function verifyProofBundle(bytes: Buffer): NodeProofBundleVerificationRecord
export declare function signProofBundleHmacSha256(proofBundle: Buffer, keyId: Buffer, secret: Buffer, context: Buffer, issuedAtMillis: string | undefined | null, expiresAtMillis: string | undefined | null, nonce: Buffer): NodeAuthenticatedProofEnvelopeRecord
export declare function verifyAuthenticatedProofEnvelope(envelope: NodeAuthenticatedProofEnvelopeRecord, secret: Buffer, nowMillis?: string | undefined | null): NodeAuthenticatedProofEnvelopeVerificationRecord
export declare function verifyAuthenticatedProofBundle(envelopeBytes: Buffer, secret: Buffer, nowMillis?: string | undefined | null): NodeAuthenticatedProofBundleVerificationRecord
export declare function authenticatedProofEnvelopeToBytes(envelope: NodeAuthenticatedProofEnvelopeRecord): Buffer
export declare function authenticatedProofEnvelopeFromBytes(bytes: Buffer): NodeAuthenticatedProofEnvelopeRecord
export declare function keyProofFromNodeBytes(root: Buffer | undefined | null, key: Buffer, pathNodeBytes: Array<Buffer>): NodeKeyProofRecord
export declare function multiKeyProofFromNodeBytes(root: Buffer | undefined | null, keys: Array<Buffer>, pathNodeBytes: Array<Buffer>): NodeMultiKeyProofRecord
export declare function rangeProofFromNodeBytes(root: Buffer | undefined | null, start: Buffer, end: Buffer | undefined | null, pathNodeBytes: Array<Buffer>): NodeRangeProofRecord
export declare function rangePageProofFromNodeBytes(root: Buffer | undefined | null, after: Buffer | undefined | null, end: Buffer | undefined | null, pathNodeBytes: Array<Buffer>): NodeRangePageProofRecord
export declare function prefixEnd(prefix: Buffer): Buffer | null
export declare function prefixRange(prefix: Buffer): NodeRangeBoundsRecord
export declare function rangeCursorStart(): NodeRangeCursorRecord
export declare function rangeCursorAfterKey(key: Buffer): NodeRangeCursorRecord
export declare function reverseCursorEnd(): NodeReverseCursorRecord
export declare function reverseCursorBeforeKey(key: Buffer): NodeReverseCursorRecord
export declare function upsertMutation(key: Buffer, value: Buffer): NodeMutationRecord
export declare function deleteMutation(key: Buffer): NodeMutationRecord
export declare function resolutionValue(value: Buffer): NodeResolutionRecord
export declare function resolutionDelete(): NodeResolutionRecord
export declare function resolutionUnresolved(): NodeResolutionRecord
export declare function resolvePreferLeft(conflict: NodeConflictRecord): NodeResolutionRecord
export declare function resolvePreferRight(conflict: NodeConflictRecord): NodeResolutionRecord
export declare function resolveDeleteWins(conflict: NodeConflictRecord): NodeResolutionRecord
export declare function resolveUpdateWins(conflict: NodeConflictRecord): NodeResolutionRecord
export declare function crdtResolutionValue(value: Buffer): NodeCrdtResolutionRecord
export declare function crdtResolutionDelete(): NodeCrdtResolutionRecord
export declare function u64Key(value: string): Buffer
export declare function u128Key(value: string): Buffer
export declare function i64Key(value: string): Buffer
export declare function i128Key(value: string): Buffer
export declare function timestampMillisKey(value: string): Buffer
export declare function encodeSegment(segment: Buffer): Buffer
export declare function keyFromSegments(segments: Array<Buffer>): Buffer
export declare function keyFromPrefixedSegments(prefix: Buffer, segments: Array<Buffer>): Buffer
export declare function changedSpan(start: Buffer, end?: Buffer | undefined | null): NodeChangedSpanRecord
export declare function changedSpanFromKey(key: Buffer): NodeChangedSpanRecord
export declare function changedSpanForPrefix(prefix: Buffer): NodeChangedSpanRecord
export declare function retainAllNamedRoots(): NodeNamedRootRetentionRecord
export declare function retainExactNamedRoots(names: Array<Buffer>): NodeNamedRootRetentionRecord
export declare function retainNamedRootPrefix(prefix: Buffer): NodeNamedRootRetentionRecord
export declare function retainNewestNamedRoots(prefix: Buffer, count: string): NodeNamedRootRetentionRecord
export declare function retainNamedRootsUpdatedSince(prefix: Buffer, minUpdatedAtMillis: string): NodeNamedRootRetentionRecord
export declare function decodeSegments(key: Buffer): Array<Buffer>
export declare function debugKey(key: Buffer): string
export declare function snapshotNamespaceBranch(): NodeSnapshotNamespaceRecord
export declare function snapshotNamespaceTag(): NodeSnapshotNamespaceRecord
export declare function snapshotNamespaceCheckpoint(): NodeSnapshotNamespaceRecord
export declare function snapshotNamespaceCustom(prefix: Buffer): NodeSnapshotNamespaceRecord
export declare function snapshotRootName(namespace: NodeSnapshotNamespaceRecord, id: Buffer): Buffer
export declare function snapshotIdFromName(namespace: NodeSnapshotNamespaceRecord, name: Buffer): Buffer | null
export declare function versionedValueBytesRoundTrip(bytes: Buffer): Buffer
export declare function versionedValueBytesMatchesSchema(bytes: Buffer, schema: string, version: string): boolean
export declare function versionedValueBytesRequireSchema(bytes: Buffer, schema: string, version: string): void
export declare function valueRefBytesRoundTrip(bytes: Buffer): Buffer
export declare function valueRefFromStoredBytes(bytes: Buffer): NodeValueRefRecord
export declare function valueRefInlineRequiresEscape(value: Buffer): boolean
export declare function blobRefValidateBytes(reference: NodeBlobRefRecord, bytes: Buffer): void
export declare function rootManifestBytesRoundTrip(bytes: Buffer): Buffer
export declare function snapshotBundleToBytes(bundle: NodeSnapshotBundleRecord): Buffer
export declare function snapshotBundleFromBytes(bytes: Buffer): NodeSnapshotBundleRecord
export declare function snapshotBundleDigest(bundle: NodeSnapshotBundleRecord): Buffer
export declare function snapshotBundleDigestBytes(bytes: Buffer): Buffer
export declare function snapshotBundleSummary(bundle: NodeSnapshotBundleRecord): NodeSnapshotBundleSummaryRecord
export declare function snapshotBundleSummaryFromBytes(bytes: Buffer): NodeSnapshotBundleSummaryRecord
export declare function verifySnapshotBundle(bundle: NodeSnapshotBundleRecord): NodeSnapshotBundleVerificationRecord
export declare function verifySnapshotBundleBytes(bytes: Buffer): NodeSnapshotBundleVerificationRecord
export declare function defaultConfig(): NodeConfigRecord
export declare function encodingRaw(): NodeEncodingRecord
export declare function encodingCbor(): NodeEncodingRecord
export declare function encodingJson(): NodeEncodingRecord
export declare function encodingCustom(name: string): NodeEncodingRecord
export declare function treeConfig(minChunkSize: string, maxChunkSize: string, chunkingFactor: number, hashSeed: string, encoding: NodeEncodingRecord, nodeCacheMaxNodes?: string | undefined | null, nodeCacheMaxBytes?: string | undefined | null): NodeConfigRecord
export declare function defaultLargeValueConfig(): NodeLargeValueConfigRecord
export declare function largeValueConfig(inlineThreshold: string): NodeLargeValueConfigRecord
export declare function defaultParallelConfig(): NodeParallelConfigRecord
export declare function parallelConfig(maxThreads: string, parallelismThreshold: string): NodeParallelConfigRecord
export declare function parallelConfigSequential(): NodeParallelConfigRecord
export declare function crdtConfigLww(deletePolicy: string): NodeCrdtConfigRecord
export declare function crdtConfigMultiValue(deletePolicy: string): NodeCrdtConfigRecord
export declare function timestampedValueToBytes(record: NodeTimestampedValueRecord): Buffer
export declare function timestampedValueFromBytes(bytes: Buffer): NodeTimestampedValueRecord
export declare function timestampedValueNow(value: Buffer): NodeTimestampedValueRecord
export declare function multiValueSetToBytes(values: Array<Buffer>): Buffer
export declare function multiValueSetFromBytes(bytes: Buffer): Array<Buffer>
export declare function multiValueSetMerge(left: Array<Buffer>, right: Array<Buffer>): Array<Buffer>
export declare function tombstoneToBytes(record: NodeTombstoneRecord): Buffer
export declare function tombstoneFromBytes(bytes: Buffer): NodeTombstoneRecord
export declare function tombstoneFromStoredBytes(bytes: Buffer): NodeTombstoneRecord | null
export declare function isTombstoneValue(bytes: Buffer): boolean
export declare function tombstoneUpsertMutation(key: Buffer, tombstone: NodeTombstoneRecord): NodeMutationRecord
export declare function tombstoneCompactionMutation(key: Buffer, storedValue: Buffer): NodeMutationRecord | null
export declare class NodePortableProximityMutationResult {
  map(): NativePortableProximityMap
  stats(): NodePortableProximityMutationStats
}
export declare class NativePortableVersionedMap {
  id(): Buffer
  headName(): Buffer
  versionsPrefix(): Buffer
  isInitialized(): boolean
  initialize(): NodePortableMapVersion
  initializeSorted(entries: Array<NodeEntryRecord>): NodePortableMapUpdate
  head(): NodePortableMapVersion | null
  headId(): Buffer | null
  version(id: Buffer): NodePortableMapVersion | null
  versions(): Array<NodePortableMapVersion>
  get(key: Buffer): Buffer | null
  getLargeValue(blobStore: NativeProllyBlobStore, key: Buffer): Buffer | null
  containsKey(key: Buffer): boolean
  getMany(keys: Array<Buffer>): Array<Buffer | undefined | null>
  getAt(id: Buffer, key: Buffer): Buffer | null
  getManyAt(id: Buffer, keys: Array<Buffer>): Array<Buffer | undefined | null>
  range(start: Buffer, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  prefix(prefix: Buffer): Array<NodeEntryRecord>
  rangeAt(id: Buffer, start: Buffer, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  prefixAt(id: Buffer, prefix: Buffer): Array<NodeEntryRecord>
  rangePage(cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeRangePageRecord
  prefixPage(prefix: Buffer, cursor: NodeRangeCursorRecord | undefined | null, limit: string): NodeRangePageRecord
  rangePageAt(id: Buffer, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeRangePageRecord
  prefixPageAt(id: Buffer, prefix: Buffer, cursor: NodeRangeCursorRecord | undefined | null, limit: string): NodeRangePageRecord
  diff(base: Buffer, target: Buffer): Array<NodeDiffRecord>
  changesSince(base: Buffer): Array<NodeDiffRecord>
  rollbackTo(id: Buffer): NodePortableMapVersion
  put(key: Buffer, value: Buffer): NodePortableMapVersion
  putLargeValue(blobStore: NativeProllyBlobStore, key: Buffer, value: Buffer, config: NodeLargeValueConfigRecord): NodePortableMapVersion
  apply(mutations: Array<NodeMutationRecord>): NodePortableMapVersion
  append(mutations: Array<NodeMutationRecord>): NodePortableMapVersion
  parallelApply(mutations: Array<NodeMutationRecord>, config: NodeParallelConfigRecord): NodePortableVersionedMapBatchResult
  rebuildSortedIf(expected: Buffer | undefined | null, entries: Array<NodeEntryRecord>): NodePortableMapUpdate
  rebuildFromEntriesIf(expected: Buffer | undefined | null, entries: Array<NodeEntryRecord>): NodePortableMapUpdate
  applyAtMillis(mutations: Array<NodeMutationRecord>, timestampMillis: string): NodePortableMapVersion
  applyIf(expected: Buffer | undefined | null, mutations: Array<NodeMutationRecord>): NodePortableMapUpdate
  applyIfAtMillis(expected: Buffer | undefined | null, mutations: Array<NodeMutationRecord>, timestampMillis: string): NodePortableMapUpdate
  putIf(expected: Buffer | undefined | null, key: Buffer, value: Buffer): NodePortableMapUpdate
  putLargeValueIf(blobStore: NativeProllyBlobStore, expected: Buffer | undefined | null, key: Buffer, value: Buffer, config: NodeLargeValueConfigRecord): NodePortableMapUpdate
  deleteIf(expected: Buffer | undefined | null, key: Buffer): NodePortableMapUpdate
  delete(key: Buffer): NodePortableMapVersion
  snapshot(): NativePortableMapSnapshot | null
  snapshotAt(id: Buffer): NativePortableMapSnapshot | null
  compare(base: Buffer, target: Buffer): NativePortableMapComparison
  compareToHead(base: Buffer): NativePortableMapComparison
  subscribe(): NativePortableMapSubscription
  subscribeFrom(lastSeen?: Buffer | undefined | null): NativePortableMapSubscription
  prepareMerge(base: Buffer, candidate: Buffer): NativePortableMapMerge
  backup(): Buffer
  restoreBackup(bytes: Buffer): NodePortableMapVersion
  importAsHead(bundle: NodeSnapshotBundleRecord): NodePortableMapVersion
  importAsHeadAtMillis(bundle: NodeSnapshotBundleRecord, timestampMillis: string): NodePortableMapVersion
  keepLast(count: number): NodePortableVersionPrune
  pruneVersions(keepLatest: string): NodePortableVersionPrune
  keepForAt(nowMillis: string, maxAgeMillis: string): NodePortableVersionPrune
  keepFor(maxAgeMillis: string): NodePortableVersionPrune
  keepVersions(ids: Array<Buffer>): NodePortableVersionPrune
  retentionPolicy(): NodeNamedRootRetentionRecord
  verifyCatalog(): NodePortableCatalogVerification
  planGc(): NodeGcPlanRecord
  sweepGc(): NodeGcSweepRecord
  planBlobGc(blobStore: NativeProllyBlobStore): NodeBlobGcPlanRecord
  sweepBlobGc(blobStore: NativeProllyBlobStore): NodeBlobGcSweepRecord
}
export declare class NativePortableMapComparison {
  base(): NodePortableMapVersion
  target(): NodePortableMapVersion
  diff(): Array<NodeDiffRecord>
  diffPage(cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeDiffPageRecord
}
export declare class NativePortableMapSubscription {
  lastSeen(): Buffer | null
  poll(): NodePortableMapChangeEvent | null
}
export declare class NativePortableMapMerge {
  base(): NodePortableMapVersion
  head(): NodePortableMapVersion
  candidate(): NodePortableMapVersion
  merge(resolver?: string | undefined | null): NodeTreeRecord
  conflictPage(cursor: NodeRangeCursorRecord | undefined | null, limit: string): NodeConflictPageRecord
  publish(resolver?: string | undefined | null): NodePortableMapUpdate
}
export declare class NativePortableVersionedTransaction {
  head(mapId: Buffer): NodePortableMapVersion | null
  get(mapId: Buffer, key: Buffer): Buffer | null
  apply(mapId: Buffer, mutations: Array<NodeMutationRecord>): NodePortableMapVersion
  applyIf(mapId: Buffer, expected: Buffer | undefined | null, mutations: Array<NodeMutationRecord>): NodePortableMapUpdate
  put(mapId: Buffer, key: Buffer, value: Buffer): NodePortableMapVersion
  delete(mapId: Buffer, key: Buffer): NodePortableMapVersion
  commit(): NodePortableVersionedTransactionCommit
  rollback(): void
}
export declare class NativePortableMapSnapshot {
  id(): Buffer
  version(): NodePortableMapVersion
  get(key: Buffer): Buffer | null
  getMany(keys: Array<Buffer>): Array<Buffer | undefined | null>
  containsKey(key: Buffer): boolean
  firstEntry(): NodeEntryRecord | null
  lastEntry(): NodeEntryRecord | null
  lowerBound(key: Buffer): NodeEntryRecord | null
  upperBound(key: Buffer): NodeEntryRecord | null
  range(start: Buffer, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  prefix(prefix: Buffer): Array<NodeEntryRecord>
  rangePage(cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeRangePageRecord
  prefixPage(prefix: Buffer, cursor: NodeRangeCursorRecord | undefined | null, limit: string): NodeRangePageRecord
  reversePage(cursor: NodeReverseCursorRecord | undefined | null, start: Buffer, limit: string): NodeReversePageRecord
  prefixReversePage(prefix: Buffer, cursor: NodeReverseCursorRecord | undefined | null, limit: string): NodeReversePageRecord
  proveKey(key: Buffer): NativePortableKeyProof
  proveKeys(keys: Array<Buffer>): NativePortableMultiKeyProof
  proveRange(start: Buffer, end?: Buffer | undefined | null): NativePortableRangeProof
  provePrefix(prefix: Buffer): NativePortableRangeProof
  proveRangePage(cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NativePortableProvedRangePage
  stats(): NodePortableMaintenanceSummary
  export(): NodeSnapshotBundleRecord
  read(): NativePortableReadSession
}
export declare class NativePortableReadSession {
  get(key: Buffer): Buffer | null
  withValueView(key: Buffer, visit: (arg: object) => void): boolean
  scanRangePages(start: Buffer, end: Buffer | undefined | null, visit: (arg: object) => number): NodePortableReadScanOutcome
}
export declare class NativePortableKeyProof {
  verify(): NodePortableProofVerification
}
export declare class NativePortableMultiKeyProof {
  verify(): NodeMultiKeyProofVerificationRecord
}
export declare class NativePortableRangeProof {
  verify(): NodeRangeProofVerificationRecord
}
export declare class NativePortableProvedRangePage {
  page(): NodeRangePageRecord
  verify(): NodeRangePageProofVerificationRecord
}
export declare class NativePortableIndexRegistry {
  constructor()
  register(name: Buffer, generation: string, extractorId: string, projection: string, limits: NodePortableSecondaryIndexLimits | undefined | null, extractor: NodePortableIndexExtractor): void
}
export declare class NativePortableIndexedMap {
  id(): Buffer
  get(key: Buffer): Buffer | null
  withValueView(key: Buffer, visit: (arg: object) => void): boolean
  put(key: Buffer, value: Buffer): NodePortableIndexedVersion
  apply(mutations: Array<NodeMutationRecord>): NodePortableIndexedVersion
  applyIf(expectedSource: Buffer | undefined | null, mutations: Array<NodeMutationRecord>): NodePortableIndexedUpdate
  delete(key: Buffer): NodePortableIndexedVersion
  ensureIndex(name: Buffer): NodePortableIndexBuildResult
  snapshot(): NativePortableIndexedSnapshot
  snapshotAt(sourceVersion: Buffer): NativePortableIndexedSnapshot
  snapshotById(snapshotId: NodePortableIndexedSnapshotId): NativePortableIndexedSnapshot
  health(): NodePortableIndexedMapHealth
  metrics(): NodePortableIndexedMapMetrics
  verifyIndex(name: Buffer, sourceVersion: Buffer): NodePortableIndexVerification
  verifyAll(sourceVersion: Buffer): Array<NodePortableIndexVerification>
  repairIndex(name: Buffer, sourceVersion: Buffer): NodePortableIndexVerification
  deactivateIndex(name: Buffer): NodePortableIndexedVersion
  exportCurrent(): Buffer
  importCurrent(bundle: Buffer, expectedSource?: Buffer | undefined | null): NodePortableIndexedVersion
  keepLast(count: string): NodePortableIndexedRetention
  planGc(): NodeGcPlanRecord
  replaceIndex(name: Buffer, generation: string, extractorId: string, projection: string, limits: NodePortableSecondaryIndexLimits | undefined | null, extractor: NodePortableIndexExtractor): NodePortableIndexBuildResult
}
export declare class NativePortableIndexedSnapshot {
  id(): NodePortableIndexedSnapshotId
  index(name: Buffer): NativePortableSecondaryIndex
}
export declare class NativePortableSecondaryIndex {
  name(): Buffer
  fastHandle(): string
  exact(term: Buffer): Array<NodePortableIndexMatch>
  prefix(prefix: Buffer): Array<NodePortableIndexMatch>
  range(start: Buffer, end?: Buffer | undefined | null): Array<NodePortableIndexMatch>
  records(term: Buffer): Array<NodePortableIndexedSource>
  exactPage(term: Buffer, cursor: Buffer | undefined | null, limit: string): NodePortableIndexPage
  exactReversePage(term: Buffer, cursor: Buffer | undefined | null, limit: string): NodePortableIndexPage
  prefixPage(prefix: Buffer, cursor: Buffer | undefined | null, limit: string): NodePortableIndexPage
  prefixReversePage(prefix: Buffer, cursor: Buffer | undefined | null, limit: string): NodePortableIndexPage
  rangePage(start: Buffer, end: Buffer | undefined | null, cursor: Buffer | undefined | null, limit: string): NodePortableIndexPage
  rangeReversePage(start: Buffer, end: Buffer | undefined | null, cursor: Buffer | undefined | null, limit: string): NodePortableIndexPage
}
export declare class NativePortableProximitySearchRuntime {
  policy(): NodePortableProximitySearchRuntimePolicy
  stats(): NodePortableProximitySearchRuntimeStats
  clear(): void
}
export declare class NativePortableProximityCancellationToken {
  constructor()
  cancel(): void
  isCancelled(): boolean
}
export declare class NativePortableHnswBuildResult {
  index(): NativePortableHnswIndex
  stats(): NodePortableHnswBuildStats
}
export declare class NativePortableHnswIndex {
  manifest(): Buffer
  sourceDescriptor(): Buffer
  config(): NodePortableHnswConfig
  isCanonical(): boolean
  search(map: NativePortableProximityMap, request: NodePortableSearchRequest): NodePortableSearchResult
  searchWithRuntime(map: NativePortableProximityMap, request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime): NodePortableSearchResult
  searchCancellable(map: NativePortableProximityMap, request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime | undefined | null, cancellation: NativePortableProximityCancellationToken): Promise<unknown>
  proveSearch(map: NativePortableProximityMap, request: NodePortableSearchRequest): NativePortableProximitySearchProof
}
export declare class NativePortablePqBuildResult {
  index(): NativePortableProductQuantizer
  stats(): NodePortablePqBuildStats
}
export declare class NativePortableProductQuantizer {
  manifest(): Buffer
  sourceDescriptor(): Buffer
  config(): NodePortablePqConfig
  quality(): NodePortablePqQuality
  search(map: NativePortableProximityMap, request: NodePortableSearchRequest): NodePortableSearchResult
  searchWithRuntime(map: NativePortableProximityMap, request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime): NodePortableSearchResult
  searchCancellable(map: NativePortableProximityMap, request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime | undefined | null, cancellation: NativePortableProximityCancellationToken): Promise<unknown>
  proveSearch(map: NativePortableProximityMap, request: NodePortableSearchRequest): NativePortableProximitySearchProof
}
export declare class NativePortableCompositeBuildResult {
  accelerator(): NativePortableCompositeAccelerator | null
  reasons(): Array<NodePortableFullRebuildReason>
  stats(): NodePortableCompositeBuildStats
}
export declare class NativePortableCompositeBuildOrRebuildResult {
  kind(): string
  composite(): NativePortableCompositeAccelerator | null
  hnsw(): NativePortableHnswIndex | null
  pq(): NativePortableProductQuantizer | null
  reasons(): Array<NodePortableFullRebuildReason>
  compositeStats(): NodePortableCompositeBuildStats
  hnswStats(): NodePortableHnswBuildStats | null
  pqStats(): NodePortablePqBuildStats | null
}
export declare class NativePortableCompositeAccelerator {
  manifest(): Buffer
  currentSourceDescriptor(): Buffer
  baseSourceDescriptor(): Buffer
  baseKind(): string
  deltaCount(): string
  shadowCount(): string
  config(): NodePortableCompositeConfig
  buildStats(): NodePortableCompositeBuildStats
  search(map: NativePortableProximityMap, request: NodePortableSearchRequest): NodePortableSearchResult
  searchWithRuntime(map: NativePortableProximityMap, request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime): NodePortableSearchResult
  searchCancellable(map: NativePortableProximityMap, request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime | undefined | null, cancellation: NativePortableProximityCancellationToken): Promise<unknown>
  proveSearch(map: NativePortableProximityMap, request: NodePortableSearchRequest): NativePortableProximitySearchProof
}
export declare class NativePortableAcceleratorCatalog {
  manifest(): Buffer
  sourceDescriptor(): Buffer
  entries(): Array<NodePortableCatalogEntry>
  search(map: NativePortableProximityMap, request: NodePortableSearchRequest): NodePortableSearchResult
  searchWithRuntime(map: NativePortableProximityMap, request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime): NodePortableSearchResult
  searchCancellable(map: NativePortableProximityMap, request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime | undefined | null, cancellation: NativePortableProximityCancellationToken): Promise<unknown>
  proveSearch(map: NativePortableProximityMap, request: NodePortableSearchRequest): NativePortableProximitySearchProof
}
export declare class NativePortableProximityMap {
  clearContentCache(): void
  buildHnsw(config?: NodePortableHnswConfig | undefined | null, limits?: NodePortableHnswBuildLimits | undefined | null): NativePortableHnswBuildResult
  loadHnsw(manifest: Buffer): NativePortableHnswIndex
  buildPq(config: NodePortablePqConfig | undefined | null, workerThreads: string, limits?: NodePortablePqBuildLimits | undefined | null): NativePortablePqBuildResult
  loadPq(manifest: Buffer): NativePortableProductQuantizer
  buildCompositeHnsw(baseMap: NativePortableProximityMap, base: NativePortableHnswIndex, config?: NodePortableCompositeConfig | undefined | null, limits?: NodePortableCompositeBuildLimits | undefined | null): NativePortableCompositeBuildResult
  buildCompositePq(baseMap: NativePortableProximityMap, base: NativePortableProductQuantizer, config?: NodePortableCompositeConfig | undefined | null, limits?: NodePortableCompositeBuildLimits | undefined | null): NativePortableCompositeBuildResult
  buildOrRebuildCompositeHnsw(baseMap: NativePortableProximityMap, base: NativePortableHnswIndex, config?: NodePortableCompositeConfig | undefined | null, limits?: NodePortableCompositeBuildLimits | undefined | null, rebuild?: NodePortableCompositeRebuildOptions | undefined | null): NativePortableCompositeBuildOrRebuildResult
  buildOrRebuildCompositePq(baseMap: NativePortableProximityMap, base: NativePortableProductQuantizer, config?: NodePortableCompositeConfig | undefined | null, limits?: NodePortableCompositeBuildLimits | undefined | null, rebuild?: NodePortableCompositeRebuildOptions | undefined | null): NativePortableCompositeBuildOrRebuildResult
  loadComposite(manifest: Buffer): NativePortableCompositeAccelerator
  buildAcceleratorCatalog(hnsw?: NativePortableHnswIndex | undefined | null, pq?: NativePortableProductQuantizer | undefined | null, composite?: NativePortableCompositeAccelerator | undefined | null): NativePortableAcceleratorCatalog
  loadAcceleratorCatalog(manifest: Buffer): NativePortableAcceleratorCatalog
  read(): NativePortableProximityReadSession
  count(): string
  config(): NodePortableProximityConfig
  get(key: Buffer): NodePortableExactProximityRecord | null
  withRecordView(key: Buffer, visit: (arg: object) => void): boolean
  withRecordRangePage(start: Buffer, end: Buffer | undefined, after: Buffer | undefined, maxRecords: number, visitor: (page: { bytes: Buffer; recordCount: number; terminal: boolean }) => void): void
  contains(key: Buffer): boolean
  scanRecords(visitor: (record: NodePortableProximityRecord) => boolean): string
  search(request: NodePortableSearchRequest): NodePortableSearchResult
  cancellationToken(): NativePortableProximityCancellationToken
  searchCancellable(request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime | undefined | null, cancellation: NativePortableProximityCancellationToken): Promise<unknown>
  searchWithRuntime(request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime): NodePortableSearchResult
  descriptor(): Buffer
  verify(): NodePortableProximityVerification
  mutate(mutations: Array<NodePortableProximityMutation>): NodePortableProximityMutationResult
  rebuild(mutations: Array<NodePortableProximityMutation>): NativePortableProximityMap
  proveMembership(key: Buffer): NativePortableProximityProof
  proveStructure(): NativePortableProximityStructuralProof
  proveSearch(request: NodePortableSearchRequest): NativePortableProximitySearchProof
}
export declare class NativePortableProximityStructuralProof {
  verify(expectedDescriptor?: Buffer | undefined | null): NodePortableStructuralVerification
}
export declare class NativePortableProximityReadSession {
  search(request: NodePortableSearchRequest): NodePortableSearchResult
  searchWithRuntime(request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime): NodePortableSearchResult
  cancellationToken(): NativePortableProximityCancellationToken
  searchCancellable(request: NodePortableSearchRequest, runtime: NativePortableProximitySearchRuntime | undefined | null, cancellation: NativePortableProximityCancellationToken): Promise<unknown>
  get(key: Buffer): NodePortableExactProximityRecord | null
  withRecordView(key: Buffer, visit: (arg: object) => void): boolean
  withRecordRangePage(start: Buffer, end: Buffer | undefined, after: Buffer | undefined, maxRecords: number, visitor: (page: { bytes: Buffer; recordCount: number; terminal: boolean }) => void): void
  contains(key: Buffer): boolean
  scanRecords(visitor: (record: NodePortableProximityRecord) => boolean): string
  withSearchPage(query: Float32Array, k: number, visitor: (page: { bytes: Buffer; recordCount: number; terminal: boolean }) => boolean): void
  fastHandle(): string
}
export declare class NativePortableProximityProof {
  verify(expectedDescriptor?: Buffer | undefined | null): Buffer | null
}
export declare class NativePortableProximitySearchProof {
  verify(expectedDescriptor?: Buffer | undefined | null): NodePortableSearchProofVerification
}
export declare class NativeRemoteProllyEngine {
  static open(dispatcher: (request: NodeRemoteStoreRequest) => Promise<NodeRemoteStoreResponse>, config: NodeConfigRecord | null | undefined, requestId: string): Promise<NativeRemoteProllyEngine>
  create(): NodeTreeRecord
  get(tree: NodeTreeRecord, key: Buffer, requestId: string): Promise<Buffer | null>
  put(tree: NodeTreeRecord, key: Buffer, value: Buffer, requestId: string): Promise<NodeTreeRecord>
  getMany(tree: NodeTreeRecord, keys: Array<Buffer>, requestId: string): Promise<Array<Buffer | undefined | null>>
  delete(tree: NodeTreeRecord, key: Buffer, requestId: string): Promise<NodeTreeRecord>
  batch(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>, requestId: string): Promise<NodeTreeRecord>
  range(tree: NodeTreeRecord, start: Buffer, end: Buffer | undefined | null, requestId: string): Promise<Array<NodeEntryRecord>>
  loadNamedRoot(name: Buffer, requestId: string): Promise<NodeTreeRecord | null>
  publishNamedRoot(name: Buffer, tree: NodeTreeRecord, requestId: string): Promise<void>
  compareAndSwapNamedRoot(name: Buffer, expected: NodeTreeRecord | undefined | null, replacement: NodeTreeRecord | undefined | null, requestId: string): Promise<NodeNamedRootUpdateRecord>
  beginTransaction(requestId: string): Promise<NativeRemoteProllyTransaction>
  close(): void
}
export declare class NativeRemoteProllyTransaction {
  create(requestId: string): Promise<NodeTreeRecord>
  get(tree: NodeTreeRecord, key: Buffer, requestId: string): Promise<Buffer | null>
  put(tree: NodeTreeRecord, key: Buffer, value: Buffer, requestId: string): Promise<NodeTreeRecord>
  publishNamedRoot(name: Buffer, tree: NodeTreeRecord, requestId: string): Promise<void>
  commit(requestId: string): Promise<NodeTransactionUpdateRecord>
  rollback(requestId: string): Promise<void>
  close(): void
}
export declare class NativeProllyBlobStore {
  static memory(): NativeProllyBlobStore
  static file(path: string): NativeProllyBlobStore
  putBlob(bytes: Buffer): NodeBlobRefRecord
  getBlob(reference: NodeBlobRefRecord): Buffer | null
  deleteBlob(reference: NodeBlobRefRecord): void
  listBlobRefs(): Array<NodeBlobRefRecord>
  blobCount(): string
}
export declare class NativeMergePolicyRegistry {
  constructor()
  len(): string
  isEmpty(): boolean
  hasDefault(): boolean
  setDefaultResolverName(name: string): void
  setDefaultResolver(resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): void
  pushPrefixResolverName(prefix: Buffer, name: string): void
  pushPrefixResolver(prefix: Buffer, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): void
  pushExactResolverName(key: Buffer, name: string): void
  pushExactResolver(key: Buffer, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): void
}
export declare class NativeHostStore {
  constructor(get: (arg: NodeHostStoreKeyRequest) => NodeHostStoreBytesResult, put: (arg: NodeHostStorePutRequest) => NodeHostStoreUnitResult, delete: (arg: NodeHostStoreKeyRequest) => NodeHostStoreUnitResult, batch: (arg: NodeHostStoreBatchRequest) => NodeHostStoreUnitResult, publishNodes: (arg: NodeHostStorePublicationRequest) => NodeHostStoreUnitResult, batchGetOrdered: (arg: NodeHostStoreBatchGetRequest) => NodeHostStoreBatchGetResult, prefersBatchReads: (arg: NodeHostStoreEmptyRequest) => NodeHostStoreBoolResult, supportsHints: (arg: NodeHostStoreEmptyRequest) => NodeHostStoreBoolResult, getHint: (arg: NodeHostStoreHintRequest) => NodeHostStoreBytesResult, putHint: (arg: NodeHostStorePutHintRequest) => NodeHostStoreUnitResult, listNodeCids: (arg: NodeHostStoreEmptyRequest) => NodeHostStoreListBytesResult, getRoot: (arg: NodeHostStoreRootRequest) => NodeHostStoreRootResult, putRoot: (arg: NodeHostStorePutRootRequest) => NodeHostStoreUnitResult, deleteRoot: (arg: NodeHostStoreRootRequest) => NodeHostStoreUnitResult, compareAndSwapRoot: (arg: NodeHostStoreCasRootRequest) => NodeHostStoreCasResult, listRoots: (arg: NodeHostStoreEmptyRequest) => NodeHostStoreListRootsResult)
}
export declare class NativeProllyTransaction {
  create(): NodeTreeRecord
  get(tree: NodeTreeRecord, key: Buffer): Buffer | null
  put(tree: NodeTreeRecord, key: Buffer, value: Buffer): NodeTreeRecord
  delete(tree: NodeTreeRecord, key: Buffer): NodeTreeRecord
  batch(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeTreeRecord
  loadNamedRoot(name: Buffer): NodeTreeRecord | null
  publishNamedRoot(name: Buffer, tree: NodeTreeRecord): void
  deleteNamedRoot(name: Buffer): void
  compareAndSwapNamedRoot(name: Buffer, expected?: NodeTreeRecord | undefined | null, replacement?: NodeTreeRecord | undefined | null): NodeNamedRootUpdateRecord
  commit(): NodeTransactionUpdateRecord
  rollback(): void
}
export declare class NativeProllyEngine {
  proximitySearchRuntime(policy?: NodePortableProximitySearchRuntimePolicy | undefined | null): NativePortableProximitySearchRuntime
  beginVersionedTransaction(): NativePortableVersionedTransaction
  versionedMap(id: Buffer): NativePortableVersionedMap
  indexedMap(id: Buffer, registry: NativePortableIndexRegistry): NativePortableIndexedMap
  buildProximity(dimensions: number, records: Array<NodePortableProximityRecord>, threads: number): NativePortableProximityMap
  loadProximity(descriptor: Buffer): NativePortableProximityMap
  static memory(): NativeProllyEngine
  static memoryWithConfigJson(configJson: string): NativeProllyEngine
  static customStore(store: NativeHostStore): NativeProllyEngine
  static customStoreWithConfigJson(store: NativeHostStore, configJson: string): NativeProllyEngine
  static file(path: string): NativeProllyEngine
  static fileWithConfigJson(path: string, configJson: string): NativeProllyEngine
  static sqlite(path: string): NativeProllyEngine
  static sqliteWithConfigJson(path: string, configJson: string): NativeProllyEngine
  static sqliteInMemory(): NativeProllyEngine
  static sqliteInMemoryWithConfigJson(configJson: string): NativeProllyEngine
  create(): NodeTreeRecord
  beginTransaction(): NativeProllyTransaction
  put(tree: NodeTreeRecord, key: Buffer, value: Buffer): NodeTreeRecord
  deleteRange(tree: NodeTreeRecord, start: Buffer, rangeEnd: Buffer): NodeTreeRecord
  deleteRangeWithStats(tree: NodeTreeRecord, start: Buffer, rangeEnd: Buffer): NodeWriteResultRecord
  delete(tree: NodeTreeRecord, key: Buffer): NodeTreeRecord
  get(tree: NodeTreeRecord, key: Buffer): Buffer | null
  getValueRef(tree: NodeTreeRecord, key: Buffer): NodeValueRefRecord | null
  getLargeValue(blobStore: NativeProllyBlobStore, tree: NodeTreeRecord, key: Buffer): Buffer | null
  putLargeValue(blobStore: NativeProllyBlobStore, tree: NodeTreeRecord, key: Buffer, value: Buffer, config: NodeLargeValueConfigRecord): NodeTreeRecord
  getMany(tree: NodeTreeRecord, keys: Array<Buffer>): Array<Buffer | undefined | null>
  proveKey(tree: NodeTreeRecord, key: Buffer): NodeKeyProofRecord
  proveKeys(tree: NodeTreeRecord, keys: Array<Buffer>): NodeMultiKeyProofRecord
  proveRange(tree: NodeTreeRecord, start: Buffer, end?: Buffer | undefined | null): NodeRangeProofRecord
  provePrefix(tree: NodeTreeRecord, prefix: Buffer): NodeRangeProofRecord
  proveRangePage(tree: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeProvedRangePageRecord
  proveDiffPage(base: NodeTreeRecord, other: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeProvedDiffPageRecord
  batch(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeTreeRecord
  batchWithStats(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeBatchApplyResultRecord
  parallelBatch(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>, config: NodeParallelConfigRecord): NodeTreeRecord
  parallelBatchWithStats(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>, config: NodeParallelConfigRecord): NodeBatchApplyResultRecord
  buildFromEntries(entries: Array<NodeEntryRecord>): NodeTreeRecord
  buildFromSortedEntries(entries: Array<NodeEntryRecord>): NodeTreeRecord
  appendBatch(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeTreeRecord
  appendBatchWithStats(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeBatchApplyResultRecord
  firstEntry(tree: NodeTreeRecord): NodeEntryRecord | null
  lastEntry(tree: NodeTreeRecord): NodeEntryRecord | null
  lowerBound(tree: NodeTreeRecord, key: Buffer): NodeEntryRecord | null
  upperBound(tree: NodeTreeRecord, key: Buffer): NodeEntryRecord | null
  range(tree: NodeTreeRecord, start: Buffer, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  prefix(tree: NodeTreeRecord, prefix: Buffer): Array<NodeEntryRecord>
  scanRange(tree: NodeTreeRecord, start: Buffer, end: Buffer | null | undefined, visitor: (entry: NodeEntryRecord) => boolean): NodeScanOutcomeRecord
  scanPrefix(tree: NodeTreeRecord, prefix: Buffer, visitor: (entry: NodeEntryRecord) => boolean): NodeScanOutcomeRecord
  scanRangeReverse(tree: NodeTreeRecord, start: Buffer, end: Buffer | null | undefined, visitor: (entry: NodeEntryRecord) => boolean): NodeScanOutcomeRecord
  scanPrefixReverse(tree: NodeTreeRecord, prefix: Buffer, visitor: (entry: NodeEntryRecord) => boolean): NodeScanOutcomeRecord
  prefixPage(tree: NodeTreeRecord, prefix: Buffer, cursor: NodeRangeCursorRecord | undefined | null, limit: string): NodeRangePageRecord
  prefixReversePage(tree: NodeTreeRecord, prefix: Buffer, cursor: NodeReverseCursorRecord | undefined | null, limit: string): NodeReversePageRecord
  rangeAfter(tree: NodeTreeRecord, afterKey: Buffer, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  rangeFromCursor(tree: NodeTreeRecord, cursor?: NodeRangeCursorRecord | undefined | null, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  rangePage(tree: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeRangePageRecord
  reversePage(tree: NodeTreeRecord, cursor: NodeReverseCursorRecord | undefined | null, start: Buffer, limit: string): NodeReversePageRecord
  cursorWindow(tree: NodeTreeRecord, key: Buffer, end: Buffer | undefined | null, limit: string): NodeCursorWindowRecord
  diff(base: NodeTreeRecord, other: NodeTreeRecord): Array<NodeDiffRecord>
  rangeDiff(base: NodeTreeRecord, other: NodeTreeRecord, start: Buffer, end?: Buffer | undefined | null): Array<NodeDiffRecord>
  scanDiff(base: NodeTreeRecord, other: NodeTreeRecord, visitor: (diff: NodeDiffRecord) => boolean): NodeScanOutcomeRecord
  scanRangeDiff(base: NodeTreeRecord, other: NodeTreeRecord, start: Buffer, end: Buffer | null | undefined, visitor: (diff: NodeDiffRecord) => boolean): NodeScanOutcomeRecord
  diffFromCursor(base: NodeTreeRecord, other: NodeTreeRecord, cursor?: NodeRangeCursorRecord | undefined | null, end?: Buffer | undefined | null): Array<NodeDiffRecord>
  diffPage(base: NodeTreeRecord, other: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeDiffPageRecord
  conflictPage(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, limit: string): NodeConflictPageRecord
  scanConflicts(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, visitor: (conflict: NodeConflictRecord) => boolean): NodeScanOutcomeRecord
  merge(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, resolver?: string | undefined | null): NodeTreeRecord
  mergeWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): NodeTreeRecord
  mergeWithPolicy(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, policy: NativeMergePolicyRegistry): NodeTreeRecord
  crdtMerge(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, config: NodeCrdtConfigRecord): NodeTreeRecord
  crdtMergeWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, deletePolicy: string, resolver: (conflict: NodeConflictRecord) => NodeCrdtResolutionRecord): NodeTreeRecord
  mergeExplain(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, resolver?: string | undefined | null): NodeMergeExplanationRecord
  mergeExplainWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): NodeMergeExplanationRecord
  mergeExplainWithPolicy(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, policy: NativeMergePolicyRegistry): NodeMergeExplanationRecord
  mergeRange(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, start: Buffer, end?: Buffer | undefined | null, resolver?: string | undefined | null): NodeTreeRecord
  mergeRangeWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, start: Buffer, end: Buffer | null | undefined, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): NodeTreeRecord
  mergeRangeWithPolicy(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, start: Buffer, end: Buffer | undefined | null, policy: NativeMergePolicyRegistry): NodeTreeRecord
  mergePrefix(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, prefix: Buffer, resolver?: string | undefined | null): NodeTreeRecord
  mergePrefixWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, prefix: Buffer, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): NodeTreeRecord
  mergePrefixWithPolicy(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, prefix: Buffer, policy: NativeMergePolicyRegistry): NodeTreeRecord
  loadNamedRoot(name: Buffer): NodeTreeRecord | null
  loadNamedRoots(names: Array<Buffer>): NodeNamedRootSelectionRecord
  loadRetainedNamedRoots(retention: NodeNamedRootRetentionRecord): NodeNamedRootSelectionRecord
  listNamedRoots(): Array<NodeNamedRootRecord>
  listNamedRootManifests(): Array<NodeNamedRootManifestRecord>
  publishNamedRoot(name: Buffer, tree: NodeTreeRecord): void
  publishNamedRootAtMillis(name: Buffer, tree: NodeTreeRecord, timestampMillis: string): void
  deleteNamedRoot(name: Buffer): void
  compareAndSwapNamedRoot(name: Buffer, expected?: NodeTreeRecord | undefined | null, replacement?: NodeTreeRecord | undefined | null): NodeNamedRootUpdateRecord
  publishSnapshot(namespace: NodeSnapshotNamespaceRecord, id: Buffer, tree: NodeTreeRecord): void
  publishSnapshotAtMillis(namespace: NodeSnapshotNamespaceRecord, id: Buffer, tree: NodeTreeRecord, timestampMillis: string): void
  loadSnapshot(namespace: NodeSnapshotNamespaceRecord, id: Buffer): NodeTreeRecord | null
  loadSnapshots(namespace: NodeSnapshotNamespaceRecord, ids: Array<Buffer>): NodeSnapshotSelectionRecord
  listSnapshots(namespace: NodeSnapshotNamespaceRecord): Array<NodeSnapshotRecord>
  deleteSnapshot(namespace: NodeSnapshotNamespaceRecord, id: Buffer): void
  compareAndSwapSnapshot(namespace: NodeSnapshotNamespaceRecord, id: Buffer, expected?: NodeTreeRecord | undefined | null, replacement?: NodeTreeRecord | undefined | null): NodeNamedRootUpdateRecord
  compareAndSwapSnapshotAtMillis(namespace: NodeSnapshotNamespaceRecord, id: Buffer, expected: NodeTreeRecord | undefined | null, replacement: NodeTreeRecord | undefined | null, timestampMillis: string): NodeNamedRootUpdateRecord
  collectStatsJson(tree: NodeTreeRecord): string
  collectStats(tree: NodeTreeRecord): unknown
  statsDiffJson(before: NodeTreeRecord, after: NodeTreeRecord): string
  statsDiff(before: NodeTreeRecord, after: NodeTreeRecord): unknown
  debugTreeJson(tree: NodeTreeRecord): string
  debugTree(tree: NodeTreeRecord): unknown
  debugTreeText(tree: NodeTreeRecord): string
  debugCompareTreesJson(left: NodeTreeRecord, right: NodeTreeRecord): string
  debugCompareTrees(left: NodeTreeRecord, right: NodeTreeRecord): unknown
  debugCompareTreesText(left: NodeTreeRecord, right: NodeTreeRecord): string
  cacheStats(): NodeCacheStatsRecord
  clearCache(): void
  pinTreeRoot(tree: NodeTreeRecord): string
  pinTreePath(tree: NodeTreeRecord, key: Buffer): string
  unpinAllCacheNodes(): string
  metrics(): NodeMetricsRecord
  resetMetrics(): void
  publishPrefixPathHint(tree: NodeTreeRecord, prefix: Buffer): boolean
  hydratePrefixPathHint(tree: NodeTreeRecord, prefix: Buffer): boolean
  publishChangedSpansHint(base: NodeTreeRecord, changed: NodeTreeRecord, spans: Array<NodeChangedSpanRecord>): boolean
  loadChangedSpansHint(base: NodeTreeRecord, changed: NodeTreeRecord): NodeChangedSpanHintRecord | null
  structuralDiffPage(base: NodeTreeRecord, other: NodeTreeRecord, cursorJson: string | undefined | null, limit: string): NodeStructuralDiffPageRecord
  structuralDiffPageWithCursor(base: NodeTreeRecord, other: NodeTreeRecord, cursor: NodeStructuralDiffCursorRecord | undefined | null, limit: string): NodeStructuralDiffPageRecord
  markReachable(roots: Array<NodeTreeRecord>): NodeGcReachabilityRecord
  markReachableBlobs(roots: Array<NodeTreeRecord>): NodeBlobGcReachabilityRecord
  listNodeCids(): Array<Buffer>
  planGc(roots: Array<NodeTreeRecord>, candidateCids: Array<Buffer>): NodeGcPlanRecord
  sweepGc(roots: Array<NodeTreeRecord>, candidateCids: Array<Buffer>): NodeGcSweepRecord
  planStoreGc(roots: Array<NodeTreeRecord>): NodeGcPlanRecord
  sweepStoreGc(roots: Array<NodeTreeRecord>): NodeGcSweepRecord
  planStoreGcForRetention(retention: NodeNamedRootRetentionRecord): NodeGcPlanRecord
  sweepStoreGcForRetention(retention: NodeNamedRootRetentionRecord): NodeGcSweepRecord
  planBlobGc(blobStore: NativeProllyBlobStore, roots: Array<NodeTreeRecord>, candidateBlobs: Array<NodeBlobRefRecord>): NodeBlobGcPlanRecord
  sweepBlobGc(blobStore: NativeProllyBlobStore, roots: Array<NodeTreeRecord>, candidateBlobs: Array<NodeBlobRefRecord>): NodeBlobGcSweepRecord
  planBlobStoreGc(blobStore: NativeProllyBlobStore, roots: Array<NodeTreeRecord>): NodeBlobGcPlanRecord
  sweepBlobStoreGc(blobStore: NativeProllyBlobStore, roots: Array<NodeTreeRecord>): NodeBlobGcSweepRecord
  planMissingNodes(tree: NodeTreeRecord, destination: NativeProllyEngine): NodeMissingNodePlanRecord
  copyMissingNodes(tree: NodeTreeRecord, destination: NativeProllyEngine): NodeMissingNodeCopyRecord
  exportSnapshot(tree: NodeTreeRecord): NodeSnapshotBundleRecord
  importSnapshot(bundle: NodeSnapshotBundleRecord): NodeTreeRecord
}
